version: "3.8"

services:
  db:
    image: postgres:alpine
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-volumes:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-volumes:
